### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by ValeriiRohachko** [OS-IS/ai201-rogachko#1]

**Comment by ValeriiRohachko** [comment]
![repo-clone](https://github.com/user-attachments/assets/294646a4-6884-4d34-8025-6eb2b70f6a4e)

**Comment by ValeriiRohachko** [comment]
![image](https://github.com/user-attachments/assets/2d0ffbf6-c4fe-4129-a350-6ddb1bc69f34)

**Comment by ValeriiRohachko** [comment]
![image](https://github.com/user-attachments/assets/392f7040-3d70-4d30-bd99-bf5db2c5e080)

**Comment by ValeriiRohachko** [comment]
![image](https://github.com/user-attachments/assets/c5ef1e54-6440-49f1-a547-7753907e7ae4)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
