### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-rogachko#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
3) Відомо, що Git-система контроля версій використовує запити Pull Request. 
Поясніть, будь ласка, як використання такого запиту може підвищити 
безпеку процесів створення програмного продукту?

**Comment by ValeriiRohachko** [comment]
Використання системи запитів Pull Requests дозволяє мати додатковий контроль над кодом/даними які мають бути доданими до голоної гілки розробки. Тобто можна налаштувати систему таким чином, щоб код можна було змерджити тільки після того як інші розробники заапрувили його. Таким чином інші розробники мають можливість перевіріти код і виявити потенційнц помилки, перед тим як цей буде доданий до основної гілки. Якщо ж в процессі перевірки коду виявленні помилки - розробник має їх виправити.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
